---
title       : "Cancer Predictor:"
subtitle    : "A Simple Means of Assessing your Chances of Cancer"
author      : Sankarshan Acharya
job         : 
framework   : io2012        # {io2012, html5slides, shower, dzslides, ...}
highlighter : highlight.js  # {highlight.js, prettify, highlight}
hitheme     : tomorrow      # 
widgets     : []            # {mathjax, quiz, bootstrap}
mode        : selfcontained # {standalone, draft}
knit        : slidify::knit2slides
---

## Reason for App

Today, there is a rise in many different types of cancer and cancer related illnesses

As such, people need a simple means to find what their chances are to get cancer

Hence, the idea for the app is created

--- .class #id 

## How the App Works

The prediction algorithm (method) for the app is simple

The app takes the clients BMI (body mass index)

The means of calculation for BMI is simple; you merely have take your weight (in pounds or kilograms) and divide it by the square of your height (in feet or meters, the first if you picked pounds and the second if you picked kilograms)

--- .class #id 

## How the App Works (cont.)

The app works if you have a BMI between 18-35 

It is assumed that if you have other problems that are more pertinent if you have a BMI outside that range

If below, you are clearly underweight

If above, you have more weight than you need (there are of course, exception)

--- .class #id 

## Conclusion

This app is an original attempt to try and make the problem of cancer curing and cancer prevention more efficient

By doing this, one can make a quick decision of whether or not to go see a doctor or not.




